substitutions:
  can_tx_pin: GPIO22
  can_rx_pin: GPIO19

canbus:
  - platform: esp32_can
    tx_pin: ${can_tx_pin}
    rx_pin: ${can_rx_pin}
    bit_rate: 50kbps
    can_id: 0 # mandatory but we do not use it
    on_frame:
    - can_id: 0
      can_id_mask: 0
      use_extended_id: true
      then:
      - lambda: |-
          auto data_pretty = remote_transmission_request ? "n/a" : format_hex_pretty(x).c_str();
          if ((can_id & 0b11111000000000011111111000000) == 0b00000000000000000000001000000)
            ESP_LOGD("comfoair_dump", "Node: %d, PDO: %d, rtr: %d, length: %d, content: %s (can_id: 0x%08x)", can_id & 0x3f, can_id >> 14, remote_transmission_request, x.size(), data_pretty, can_id);
          else
            ESP_LOGV("comfoair_dump", "can_id: 0x%08x, rtr: %d, length: %d, content: %s", can_id, remote_transmission_request, x.size(), data_pretty);
