.throttle-filter: &throttle-filter
  - throttle_average: '${filter_time}'
  - filter_out: nan
  - sliding_window_moving_average: {send_every: '${filter_send_every}', window_size: '${filter_window_size}'}

binary_sensor:
  - platform: template
    id: manual_mode     # PDO 72 (raw)
    name: 'Manual mode'
    icon: mdi:check-circle

  - platform: template
    id: pdo_115     # PDO 115 (raw)
    name: 'PDO 115'
    icon: mdi:check-circle

  - platform: template
    id: pdo_116     # PDO 116 (raw)
    name: 'PDO 116'
    icon: mdi:check-circle

  - platform: template
    id: pdo_229     # PDO 229 (raw)
    name: 'PDO 229'
    icon: mdi:check-circle

sensor:
  - platform: template
    id: comfortcontrol_mode # PDO 225 
    name: 'Sensor based ventilation mode'
    # accuracy_decimals: 0
    # unit_of_measurement: '%'
    # state_class: measurement

  - platform: template
    id: fan_speed_mode_modulated # PDO 226
    name: 'Fan Speed (modulated)'
    # accuracy_decimals: 0
    # unit_of_measurement: '%'
    # state_class: measurement

  - platform: template
    id: pdo_273 # PDO 273
    name: 'PDO 273 delta T?'
    filters: [multiply: 0.1]
    accuracy_decimals: 1
    unit_of_measurement: '°C'
    device_class: temperature
    state_class: measurement

  - platform: template
    id: exhaust_fan_power # PDO 305
    name: 'Exhaust fan power'
    filters: [multiply: 0.1]
    accuracy_decimals: 2
    unit_of_measurement: 'W'
    device_class: power
    state_class: measurement
    filters: *throttle-filter

  - platform: template
    id: supply_fan_power # PDO 306
    name: 'Supply fan power'
    filters: [multiply: 0.1]
    accuracy_decimals: 2
    unit_of_measurement: 'W'
    device_class: power
    state_class: measurement
    filters: *throttle-filter

  - platform: template
    id: analog_input_0_10v_1 # PDO 369
    name: 'analog_input_0_10v_1'
    filters: [multiply: 0.1]
    accuracy_decimals: 2
    unit_of_measurement: 'V'
    device_class: voltage
    state_class: measurement

  - platform: template
    id: analog_input_0_10v_2 # PDO 370
    name: 'analog_input_0_10v_2'
    filters: [multiply: 0.1]
    accuracy_decimals: 2
    unit_of_measurement: 'V'
    device_class: voltage
    state_class: measurement

  - platform: template
    id: analog_input_0_10v_3 # PDO 371
    name: 'analog_input_0_10v_3'
    filters: [multiply: 0.1]
    accuracy_decimals: 2
    unit_of_measurement: 'V'
    device_class: voltage
    state_class: measurement

  - platform: template
    id: analog_input_0_10v_4 # PDO 372
    name: 'analog_input_0_10v_4'
    filters: [multiply: 0.1]
    accuracy_decimals: 2
    unit_of_measurement: 'V'
    device_class: voltage
    state_class: measurement

  - platform: template
    id: pdo_385 # PDO 385
    name: 'PDO 385'
    # accuracy_decimals: 0
    # unit_of_measurement: '%'
    # state_class: measurement

  - platform: template
    id: pdo_401 # PDO 401
    name: 'PDO 401'
    # accuracy_decimals: 0
    # unit_of_measurement: '%'
    # state_class: measurement

 - platform: template
    id: comfofond_ghe_state_perc # PDO 418
    name: 'ComfoFond GHE State Percentage'
    accuracy_decimals: 0
    unit_of_measurement: '%'
    state_class: measurement

text_sensor:
  - platform: template
    id: airflow_constraints # PDO 230
    name: 'Airflow constraints'
    # accuracy_decimals: 0
    # unit_of_measurement: '%'
    # state_class: measurement

