.throttle-filter: &throttle-filter
  - throttle_average: '${filter_time}'
  - filter_out: nan
  - sliding_window_moving_average: {send_every: '${filter_send_every}', window_size: '${filter_window_size}'}

.throttle-filter-e-1: &throttle-filter-e-1
  - throttle_average: '${filter_time}'
  - filter_out: nan
  - sliding_window_moving_average: {send_every: '${filter_send_every}', window_size: '${filter_window_size}'}
  - multiply: 0.1  

binary_sensor:
  # - platform: template
  #   id: manual_mode # PDO 56 (raw)
  #   name: 'Manual Mode'
  #   icon: mdi:check-circle
  - platform: template
    id: manual_mode_2 # PDO 72 (raw)
    name: 'Manual Mode 2'
    icon: mdi:check-circle
  - platform: template
    id: pdo_115     # PDO 115 (raw)
    name: 'PDO 115'
    icon: mdi:check-circle
  - platform: template
    id: pdo_116     # PDO 116 (raw)
    name: 'PDO 116'
    icon: mdi:check-circle
  - platform: template
    id: pdo_229     # PDO 229 (raw)
    name: 'PDO 229'
    icon: mdi:check-circle
  - platform: template
    id: pdo_386     # PDO 386 (raw)
    name: 'PDO 386'
    icon: mdi:check-circle
  - platform: template
    id: pdo_402     # PDO 402 (raw)
    name: 'PDO 402'
    icon: mdi:check-circle

  - platform: template
    id: comfocool_state # PDO 784
    name: 'ComfoCool State'
    icon: mdi:check-circle
  - platform: template
    id: pdo_785 # PDO 785 (raw)
    name: 'PDO 785'
    icon: mdi:check-circle

sensor:
  - platform: template
    id: supply_fan_next_change_raw # PDO 86
    name: 'supply_fan_next_change_raw'
    accuracy_decimals: 0
    device_class: duration
    unit_of_measurement: 's'
    internal: true
    on_value:
      then:
        - lambda: id(supply_fan_next_change_in).publish_state(id(comfoair)->seconds_to_human_readable(x));

  - platform: template
    id: exhaust_fan_next_change_raw # PDO 87
    name: 'exhaust_fan_next_change_raw'
    accuracy_decimals: 0
    device_class: duration
    unit_of_measurement: 's'
    internal: true
    on_value:
      then:
        - lambda: id(exhaust_fan_next_change_in).publish_state(id(comfoair)->seconds_to_human_readable(x));


  - platform: template
    id: fan_speed_mode_modulated # PDO 226
    name: 'Fan Speed (modulated)'
    # accuracy_decimals: 0
    # unit_of_measurement: '%'
    # state_class: measurement

  - platform: template
    id: airflow_constraints_raw # PDO 230
    name: 'airflow_constraints_raw'
    accuracy_decimals: 0
    # internal: true
    on_value:
      then:
        - lambda: |-
            std::vector<std::string> constraints = id(comfoair)->calculate_airflow_constraints(x);
            if (!constraints.empty()) {
              id(airflow_constraints).publish_state(constraints[0]);
            } else {
              id(airflow_constraints).publish_state("");
            }

  - platform: template
    id: pdo_273 # PDO 273
    name: 'PDO 273 delta T?'
    filters: [multiply: 0.1]
    accuracy_decimals: 1
    unit_of_measurement: '째C'
    device_class: temperature
    state_class: measurement

  - platform: template
    id: exhaust_fan_power # PDO 305
    name: 'Exhaust fan power'
    accuracy_decimals: 0
    unit_of_measurement: 'W'
    device_class: power
    state_class: measurement
    filters:  *throttle-filter-e-1
 
  - platform: template
    id: supply_fan_power # PDO 306
    name: 'Supply fan power'
    accuracy_decimals: 0
    unit_of_measurement: 'W'
    device_class: power
    state_class: measurement
    filters:  *throttle-filter-e-1
 
  - platform: template
    id: analog_input_0_10v_1 # PDO 369
    name: 'analog_input_0_10v_1'
    filters: [multiply: 0.1]
    accuracy_decimals: 2
    unit_of_measurement: 'V'
    device_class: voltage
    state_class: measurement

  - platform: template
    id: analog_input_0_10v_2 # PDO 370
    name: 'analog_input_0_10v_2'
    filters: [multiply: 0.1]
    accuracy_decimals: 2
    unit_of_measurement: 'V'
    device_class: voltage
    state_class: measurement

  - platform: template
    id: analog_input_0_10v_3 # PDO 371
    name: 'analog_input_0_10v_3'
    filters: [multiply: 0.1]
    accuracy_decimals: 2
    unit_of_measurement: 'V'
    device_class: voltage
    state_class: measurement

  - platform: template
    id: analog_input_0_10v_4 # PDO 372
    name: 'analog_input_0_10v_4'
    filters: [multiply: 0.1]
    accuracy_decimals: 2
    unit_of_measurement: 'V'
    device_class: voltage
    state_class: measurement

  - platform: template
    id: pdo_384 # PDO 384
    name: 'PDO 384'
    filters: [multiply: 0.1]
    # accuracy_decimals: 0
    # unit_of_measurement: '%'
    # state_class: measurement

  - platform: template
    id: pdo_385 # PDO 385
    name: 'PDO 385'
    # accuracy_decimals: 0
    # unit_of_measurement: '%'
    # state_class: measurement

  - platform: template
    id: pdo_400 # PDO 400
    name: 'PDO 400'
    filters: [multiply: 0.1]
    # accuracy_decimals: 0
    # unit_of_measurement: '%'
    # state_class: measurement

  - platform: template
    id: pdo_401 # PDO 401
    name: 'PDO 401'
    # accuracy_decimals: 0
    # unit_of_measurement: '%'
    # state_class: measurement

  - platform: template
    id: comfofond_temp_outdoor # PDO 416
    name: 'ComfoFond Outdoor Air Temperature'
    filters: [multiply: 0.1]
    accuracy_decimals: 1
    unit_of_measurement: '째C'
    device_class: temperature
    state_class: measurement

  - platform: template
    id: comfofond_temp_ground # PDO 417
    name: 'ComfoFond Ground Temperature'
    filters: [multiply: 0.1]
    accuracy_decimals: 1
    unit_of_measurement: '째C'
    device_class: temperature
    state_class: measurement

  - platform: template
    id: comfofond_ghe_state_perc # PDO 418
    name: 'ComfoFond GHE State Percentage'
    accuracy_decimals: 0
    unit_of_measurement: '%'
    state_class: measurement
    filters: *throttle-filter

  # - platform: template
  #   id: comfocool_state # PDO 784
  #   name: 'ComfoCool State'
  #   accuracy_decimals: 0
  #   unit_of_measurement: '%'
  #   state_class: measurement
  #   filters: *throttle-filter

  - platform: template
    id: comfocool_temp_condensor # PDO 802
    name: 'ComfoCool Condensor Temperature'
    filters: [multiply: 0.1]
    accuracy_decimals: 1
    unit_of_measurement: '째C'
    device_class: temperature
    state_class: measurement

text_sensor:

  - platform: template
    id: manual_mode # PDO 56 (raw)
    name: 'Manual Mode'
    filters:
      - map:
        - 0 -> Unlimited Manual
        - 255 -> Auto

  - platform: template
    id: supply_fan_mode_2 # PDO 70
    name: 'Supply Fan Mode 2'
    icon: mdi:arrow-split-vertical
    filters:
      - map:
        - 0 -> Balanced
        - 1 -> Supply Only

  - platform: template
    id: exhaust_fan_mode_2 # PDO 71
    name: 'Exhaust Fan Mode 2'
    icon: mdi:arrow-split-vertical
    filters:
      - map:
        - 0 -> Balanced
        - 1 -> Supply Only

  - platform: template
    id: supply_fan_next_change_in # PDO 86 (raw)
    name: 'Supply Fan Next Change In'

  - platform: template
    id: exhaust_fan_next_change_in # PDO 87 (raw)
    name: 'Exhaust Fan Next Change In'

  - platform: template
    id: comfortcontrol_mode # PDO 225 
    name: 'Sensor based ventilation mode'
    filters:
      - map:
        - 0 -> Disabled
        - 1 -> Active
        - 2 -> Overruling

  - platform: template
    id: airflow_constraints # PDO 230
    name: 'Airflow constraints'
    icon: mdi:fan-alert

  - platform: template
    id: supply_fan_mode_3 # PDO 342
    name: 'Supply Fan Mode 3'
    icon: mdi:arrow-split-vertical
    filters:
      - map:
        - 0 -> Balanced
        - 2 -> Supply Only

  - platform: template
    id: exhaust_fan_mode_3 # PDO 343
    name: 'Exhaust Fan Mode 3'
    icon: mdi:arrow-split-vertical
    filters:
      - map:
        - 0 -> Balanced
        - 2 -> Supply Only

  - platform: template
    id: comfofond_ghe_present # PDO 419 (raw)
    name: 'ComfoFond GHE Present'
    icon: mdi:arrow-split-vertical
    filters:
      - map:
        - 0 -> absent
        - 1 -> present
